// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"github.com/hyperledger/fabric/common/replication"
	mock "github.com/stretchr/testify/mock"
)

// VerifierRetriever is an autogenerated mock type for the VerifierRetriever type
type VerifierRetriever struct {
	mock.Mock
}

// RetrieveVerifier provides a mock function with given fields: channel
func (_m *VerifierRetriever) RetrieveVerifier(channel string) replication.BlockVerifier {
	ret := _m.Called(channel)

	var r0 replication.BlockVerifier
	if rf, ok := ret.Get(0).(func(string) replication.BlockVerifier); ok {
		r0 = rf(channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(replication.BlockVerifier)
		}
	}

	return r0
}
